// Generated by CoffeeScript 1.6.3
(function() {
  var log, printMatrix, randomArray, randomInt, randomIntInRange, randomMatrix;

  randomInt = function(n) {
    return parseInt(Math.random() * n);
  };

  randomIntInRange = function(min, max) {
    return randomInt(max + 1 - min) + min;
  };

  randomMatrix = function(m, n, min, max) {
    var i, j, matrix, _i, _j;
    matrix = [];
    for (i = _i = 0; 0 <= m ? _i < m : _i > m; i = 0 <= m ? ++_i : --_i) {
      matrix[i] = [];
      for (j = _j = 0; 0 <= n ? _j < n : _j > n; j = 0 <= n ? ++_j : --_j) {
        matrix[i][j] = randomIntInRange(min, max);
      }
    }
    return matrix;
  };

  randomArray = function(n, min, max) {
    var array, i, _i;
    array = [];
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      array[i] = randomIntInRange(min, max);
    }
    return array;
  };

  log = function(str) {
    return process.stdout.write(str);
  };

  printMatrix = function(matrix) {
    var i, j, _i, _j, _ref, _ref1, _results;
    _results = [];
    for (i = _i = 0, _ref = matrix.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      for (j = _j = 0, _ref1 = matrix[i].length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
        if (matrix[i][j] < 10 && matrix[i][j] > -10) {
          log(' ');
        }
        if (matrix[i][j] < 100 && matrix[i][j] > -100) {
          log(' ');
        }
        if (matrix[i][j] >= 0) {
          log(' ');
        }
        log(' ' + matrix[i][j]);
      }
      _results.push(console.log(""));
    }
    return _results;
  };

  exports.randomMatrix = randomMatrix;

  exports.randomInt = randomInt;

  exports.randomArray = randomArray;

  exports.printMatrix = printMatrix;

  exports.randomIntInRange = randomIntInRange;

}).call(this);
