// Generated by CoffeeScript 1.6.3
(function() {
  "Design an algorithm and write code to remove the duplicate characters in a string without using any additional buffer NOTE: One or two additional variables are fine An extra copy of the array is not";
  var main, main2, main3;

  main = function(str) {
    var i, len, o, ret, _i;
    len = str.length;
    o = {};
    for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
      o[str[i]] = true;
    }
    ret = "";
    for (i in o) {
      ret += i;
    }
    return ret;
  };

  main2 = function(str) {
    var arr, i, len, _i;
    len = str.length;
    arr = [];
    for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
      if (arr.indexOf(str[i]) !== -1) {
        continue;
      }
      arr.push(str[i]);
    }
    return arr.join('');
  };

  main3 = function(str) {
    var i, j, len, ret, _i, _j, _ref;
    len = str.length;
    ret = "";
    for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
      for (j = _j = _ref = i + 1; _ref <= len ? _j < len : _j > len; j = _ref <= len ? ++_j : --_j) {
        console.log("i: " + str[i]);
        console.log("j: " + str[j]);
        if (str[i] !== str[j] && i !== j) {
          ret += str[i];
        }
      }
    }
    return ret;
  };

  console.log(main3('abab'));

  "console.log main('abab')\nconsole.log main('aa')\nconsole.log main('aabb')\nconsole.log main('abc')\n\n\nconsole.log main2('abab')\nconsole.log main2('aa')\nconsole.log main2('aabb')\nconsole.log main2('abc')";

}).call(this);
